[versions]
agp = "8.6.0-alpha07"
leanback = "1.0.0"
glide = "4.11.0"

[libraries]
androidx-leanback = { group = "androidx.leanback", name = "leanback", version.ref = "leanback" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
exoplayer = "com.google.android.exoplayer:exoplayer:2.19.1"
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

